#!/bin/sh

# File:     aliases
# Created:  30.12.2019
# Author:   Artyom Danilov (@defytheflow)


alias sudo='sudo ' # Run 'sudo {alias}'

alias e='exa'
alias f='file'
alias g='git'
alias h='history'
alias j='java'
alias l='ls'
alias s='source'
alias t='tree'

alias cl='clear'
alias gh='history | grep'
alias jc='javac'
alias me='curl https://ipinfo.io/ip'
alias sc='shellcheck'

alias sch='shellcheck'
alias stl='systemctl'
alias open='xdg-open'

# cd
alias ..='cd ..'
alias ...='cd ../../'
alias ....=' cd ../../../'
alias .....='cd ../../../../'
alias -- -='cd -'  # Type '-' to go to previous dir.

# pip
alias pip='pip3'

# python
alias py='python3'
alias python='python3'
alias ipy='ipython3'
alias ipython='ipython3'

# django
alias djsa='django-admin startapp'
alias djch='django-admin check'
alias djdb='django-admin dbshell'
alias djm='django-admin migrate'
alias djmm='django-admin makemigrations'
alias djr='django-admin runserver'
alias djsh='django-admin shell'
alias djsu='django-admin createsuperuser'
alias djt='django-admin test'

# vim
alias nv='nvim'
alias vi='vim'
alias snv='sudo nvim'

# git
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcl='git clone'
alias gch='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log'
alias glg='git log --grep'
alias gm='git merge'
alias gmv='git mv'
alias gp='git push'
alias gpf='git push --force'
alias gpl='git pull'
alias grb='git rebase -i'
alias grm='git rm'
alias grl='git rev-list --count HEAD'
alias grs='git reset'
alias grv='git revert'
alias gs='git status'
alias gsh='git show'
alias gst='git stash'

# ls
alias ls='ls -vh --color=auto --group-directories-first'
alias la='ls -A'
alias lal='ls -Al'
alias lh='ls -d .*'
alias ll='ls -l'
alias lr='ls -r'

# exa
alias exa='exa --icons --group-directories-first -I "__pycache__|plugged|node_modules|.git"'
alias ea='exa -a'
alias el='exa -l'
alias et='exa -T'
alias eta='exa -Ta'

# grep
alias grep='grep --color=auto'
alias igrep='grep -i'

# diff
alias diff='diff --side-by-side --suppress-common-lines --color=auto'

# tree
alias tree='tree -C -I .git'
alias ta='tree -a'
alias td='tree -d'
alias tl='tree -a -L 2'

# files
alias cp='cp -iv'
alias du='du -h'
alias md='mkdir -pv'
alias mv='mv -iv'
alias rd='rmdir -v'
alias rm='rm -vi --preserve-root '
alias rr='rm -rfi'
alias smv='sudo mv'
alias smd='sudo mkdir'
alias srd='sudo rmdir'
alias srm='sudo rm'
alias tc='touch'
alias stc='sudo touch'

# ssh
alias ssh='TERM=xterm-color ssh'  # 'tput: unknown terminal bug'

# windows
alias cls='clear'
alias copy='cp'
alias edit='nvim'
alias move='mv'
alias rename='mv'

# config
alias tmux='tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf'
alias wget='wget --hsts-file=${XDG_CACHE_HOME}/wget-hsts'

# commands
alias path='echo ${PATH} | sed -e "s|:|\n|g"'
alias xrld='source ~/.xprofile'

# dirs
alias dot='cd ~/.dotfiles'
alias work='cd ~/dev/repos/work'
alias pers='cd ~/dev/repos/personal'
alias sand='cd ~/dev/sand'

# fun
alias starwars='telnet towel.blinkenlights.nl'

# wsl
if [ -n "${WSL_DISTRO_NAME}" ]; then
    alias ls='ls --color=never -F'  # on windows terminals 'ls' colors are awful.
fi
