#!/bin/sh

# File:      shell/alias
# Purpose:   Define shortcuts for commands and add default arguments.
# Notes:     This file is sourced by .zshrc and .bashrc accordingly.

# Created:   30.12.2019
# Author:    Artyom Danilov
# Caution:   Order is important, some aliases can and will break if you change it


# Allow running sudo with aliases.
alias sudo='sudo '

alias jc='javac'
alias j='java'

# cd {{{
alias \
    ..='cd ..' \
    ...='cd ../../' \
    ....=' cd ../../../' \
    .....='cd ../../../../'
# Typing mistakes.
alias \
    cd..='cd ..' \
    cd~='cd ~'   \
    cd-='cd -'   \
    CD='cd'
# Type '-' to go to previous dir.
alias -- -='cd -'
#}}}

# cp {{{
alias cp='cp -iv'
#}}}

# cat {{{
alias \
    nc='cat -n' \
    cc='highlight --out-format=ansi --force'
#}}}

# diff {{{
alias \
    diff='diff -y --suppress-common-lines' \
    diff='diff --color=auto'
#}}}

# dir {{{
alias \
    dir='dir --color=auto'  \
    vdir='vdir --color=auto'
#}}}

# du {{{
alias du='du -h'
#}}}

# exa {{{
alias \
    ex='exa --icons --group-directories-first --git-ignore -I __pycache__' \
    e='ex -1'  \
    ea='ex -a' \
    el='ex -l' \
    er='ex -R' \
    et='ex -T'
#}}}

# grep{{{
alias \
    grep='grep --color=auto'   \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto'
#}}}

# ls {{{
alias \
    ls='ls -vhF --color=never --group-directories-first' \
    l='  ls -1'    \
    la=' ls -A'    \
    lh=' ls -d .*' \
    ll=' ls -l'    \
    lr=' ls -r'    \
    lal='ls -Al'   \
    LS=ls
#}}}

# mkdir {{{
alias \
    mkdir='mkdir -pv' \
    mkd='mkdir'
#}}}

# mv {{{
alias mv='mv -iv'
#}}}

# rmdir {{{
alias \
    rmdir='rmdir -v' \
    rmd='rmdir'
#}}}

# rm {{{
alias \
    rm='rm -vI --preserve-root ' \
    rr='rm -rfI'
#}}}

# tree {{{
alias \
    tree='tree -I .git' \
    ta='tree -a'        \
    td='tree -d'        \
    t='tree'
#}}}

# Shortcuts [a-z] {{{
alias \
    f='file'    \
    g='git'     \
    h='history' \
    n='ls -A | wc -l' \
    p='pwd'     \
    s='source'  \
    v='vim'
#}}}

# Shortcuts [a-z]{2} {{{
alias \
    gh='history | grep' \
    py='python3'        \
    sc='shellcheck'     \
    tc='touch'          \
    vi='vim'
#}}}

# Shortcuts [a-z]{3} {{{
alias \
    clr='clear'   \
    shu='shunit2'
#}}}

# Shortcuts (other).
alias chrome='google-chrome'

# Sudo priveleges {{{
alias \
    scp='sudo cp'        \
    smv='sudo mv'        \
    srm='sudo rm'        \
    snvim='sudo nvim'    \
    smkdir='sudo mkdir'  \
    srmdir='sudo rmdir'  \
    reboot='sudo reboot' \
    shutdown='sudo shutdown'
#}}}

# Windows cmd {{{
alias \
    edit='vim'  \
    del='rm'    \
    cls='clear' \
    copy='cp'   \
    move='mv'   \
    rename='mv'
#}}}

# Curls {{{
alias \
    corona='curl https://corona-stats.online'            \
    coronaru='curl "https://corona-stats.online/Russia"' \
    starwars='telnet towel.blinkenlights.nl'             \
    weather='curl http://wttr.in/'
#}}}

# Version conflicts {{{
alias \
    pip='pip3'       \
    pylint='pylint3' \
    python='python3'
#}}}

# Config/History files locations {{{
alias \
    wget='wget --hsts-file=${XDG_CACHE_HOME}/wget-hsts' \
    tmux='tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf'
#}}}

# Print time (e.g. 13:29:43)
alias now='date +\"%T\"'
# List every dir in PATH on a separate line.
alias path='echo ${PATH} | sed -e "s|:|\n|g"'
# Open application store.
alias store='ubuntu-software'
# Fast way to update packages.
alias update='sudo apt-get update;sudo apt-get upgrade;sudo apt-get autoremove'

command -v exa >/dev/null && \
    alias l='ex' \
    alias t='et'
