#!/bin/sh

# File:     aliases
# Created:  30.12.2019
# Author:   Artyom Danilov (@defytheflow)

alias sudo='sudo ' # Run 'sudo {alias}'

alias e='exa'
alias f='file'
alias g='git'
alias h='history'
alias j='java'
alias p='pacman'
alias t='tree'

alias cl='clear'
alias fr='free -h'
alias jc='javac'
alias me='curl https://ipinfo.io/ip'
alias sc='shellcheck'
alias so='source'

alias sch='shellcheck'
alias stl='systemctl'
alias open='xdg-open'
alias sqlite='sqlite3'

# cd
alias ..='cd ..'
alias ...='cd ../../'
alias ....=' cd ../../../'
alias .....='cd ../../../../'
alias -- -='cd -' # Type '-' to go to previous dir.

# pip
alias pip='pip3'

# python
alias py='python3'
alias python='python3'
alias ipy='ipython3'
alias ipython='ipython3'

# django
alias dj='django-admin'
alias djch='django-admin check'
alias djdb='django-admin dbshell'
alias djm='django-admin migrate'
alias djmm='django-admin makemigrations'
alias djr='django-admin runserver'
alias djsa='django-admin startapp'
alias djsh='django-admin shell'
alias djsm='django-admin showmigrations'
alias djsp='django-admin startproject'
alias djsql='django-admin sqlmigrate'
alias djsu='django-admin createsuperuser'
alias djt='django-admin test'

# vim
alias nv='nvim'
alias vi='nvim'
alias vim='nvim'

# git
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcl='git clone'
alias gch='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log'
alias glg='git log --grep'
alias gm='git merge'
alias gmv='git mv'
alias gp='git push'
alias gpf='git push --force'
alias gpl='git pull'
alias grb='git rebase -i'
alias grm='git rm'
alias grl='git rev-list --count HEAD'
alias grs='git reset'
alias grsu="git reset 'HEAD@{1}'"
alias grv='git revert'
alias gs='git status'
alias gsh='git show'
alias gst='git stash'
alias gstd='git stash drop'

# ls
alias ls='ls -vh --color=auto --group-directories-first'
alias la='ls -A'
alias lal='ls -Al'
alias lh='ls -d .*'
alias ll='ls -l'
alias lr='ls -r'

# exa
alias exa='exa --icons --group-directories-first -I "__pycache__|node_modules|.git"'
alias ea='exa -a'
alias el='exa -l'
alias et='exa -T'
alias eta='exa -Ta'

# grep
alias grep='grep --color=auto'
alias igrep='grep -i'

# diff
alias diff='diff --side-by-side --suppress-common-lines --color=auto'

# tree
alias tree='tree -C -I .git'
alias ta='tree -a'
alias td='tree -d'
alias tl='tree -a -L 2'

# cat
if command -v bat >/dev/null; then
  alias cat='bat'
fi

# rm.
if command -v rmtrash >/dev/null; then
  alias rm='rmtrash'
  alias rmdir='rmdirtrash'
  alias rd='rmdir'
else
  alias rm='rm -vi --preserve-root'
  alias rmdir='rmdir -vi'
  alias rd='rmdir -vi'
fi

alias srm='sudo rm'
alias srd='sudo rmdir'

# files
alias cp='cp -iv'
alias du='du -h'
alias md='mkdir -pv'
alias mv='mv -iv'
alias smv='sudo mv'
alias smd='sudo mkdir'
alias tc='touch'
alias stc='sudo touch'

# ssh
alias ssh='TERM=xterm-color ssh' # 'tput: unknown terminal bug'

# windows
alias cls='clear'
alias copy='cp'
alias del='rm'
alias edit='vim'
alias move='mv'
alias rename='mv'

# config
alias tmux='tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf'
alias wget='wget --hsts-file=${XDG_CACHE_HOME}/wget-hsts'

# commands
alias xrld='source ~/.xprofile'

# dirs
alias api='cd ${CODE_HOME}/repos/properoom-api'

# fun
alias starwars='telnet towel.blinkenlights.nl'

# wsl
if [ -n "${WSL_DISTRO_NAME}" ]; then
  alias ls='ls --color=never -F' # on windows terminals 'ls' colors are awful.
fi
