#!/bin/sh

# File:      alias
# Created:   30.12.2019
# Author:    Artyom Danilov

alias sudo='sudo ' # Run 'sudo {alias}'

alias c='highlight --out-format=ansi --force'
alias e='exa -1'
alias f='file'
alias g='git'
alias h='history'
alias j='java'
alias l='ls'
alias n='ls -A | wc -l'
alias p='pwd'
alias s='source'
alias t='tree'
alias v='vim'

alias cl='clear'
alias tl='trash-list'
alias gh='history | grep'
alias jc='javac'
alias nv='nvim'
alias py='python3'
alias sc='shellcheck'
alias tc='touch'
alias vi='vim'

alias del='trash'
alias now='date +\"%T\"'
alias open='xdg-open'
alias path='echo ${PATH} | sed -e "s|:|\n|g"'
alias shu='shunit2'
alias store='ubuntu-software'
alias update='sudo apt-get update;sudo apt-get upgrade;sudo apt-get autoremove'
alias chrome='google-chrome'
alias xrld='source ~/.xprofile'

alias ..='cd ..'
alias ...='cd ../../'
alias ....=' cd ../../../'
alias .....='cd ../../../../'
alias -- -='cd -' # Type '-' to go to previous dir.

alias ls='ls -vhF --color=never --group-directories-first'
alias la='ls -A'
alias lh='ls -d .*'
alias ll='ls -l'
alias lr='ls -r'
alias lal='ls -Al'

alias tree='tree -I .git'
alias ta='tree -a'
alias td='tree -d'

alias rm='rm -vi --preserve-root '
alias rr='rm -rfI'

alias cp='cp -iv'
alias du='du -h'
alias mv='mv -iv'

alias mkdir='mkdir -pv'
alias rmdir='rmdir -v'

alias exa='exa --icons --group-directories-first --git-ignore -I __pycache__'
alias diff='diff -y --suppress-common-lines --color=auto'
alias grep='grep --color=auto'

alias cls='clear'
alias copy='cp'
alias edit='nvim'
alias move='mv'
alias rename='mv'

alias scp='sudo cp'
alias smv='sudo mv'
alias smkdir='sudo mkdir'
alias snvim='sudo nvim'
alias srm='sudo rm'
alias srmdir='sudo rmdir'

alias pip='pip3'
alias pylint='pylint3'
alias python='python3'
alias ipython='ipython3'

alias wget='wget --hsts-file=${xdg_cache_home}/wget-hsts'
alias tmux='tmux -f ${xdg_config_home}/tmux/tmux.conf'

alias starwars='telnet towel.blinkenlights.nl'

if command -v exa >/dev/null; then
    alias l='exa'
    alias t='exa -T'
fi
