#!/bin/sh

# File:     aliases
# Created:  30.12.2019
# Author:   Artyom Danilov (@defytheflow)

alias sudo='sudo ' # Run 'sudo {alias}'

alias f='file'
alias h='history'
alias p='pwd'

alias so='source'
alias lg='lazygit'
alias vi='vim'

alias ssh='TERM=xterm-color ssh' # 'tput: unknown terminal bug'
alias diff='diff --side-by-side --suppress-common-lines --color=auto'
alias grep='grep --color=auto'
alias open='xdg-open'
alias xrld='source ~/.xprofile'

# cd.
alias ..='cd ..'
alias ...='cd ../../'
alias ....=' cd ../../../'
alias .....='cd ../../../../'
alias -- -='cd -' # Type '-' to go to previous dir.

# ls.
alias l='ls -1'
alias ls='ls -vh --group-directories-first'
alias la='ls -A'
alias ll='ls -l'

# files.
alias cp='cp -iv'
alias du='du -h'
alias md='mkdir -pv'
alias mv='mv -iv'
alias tc='touch'
alias rd='rmdir'
alias rm='rm -vi --preserve-root'
alias rmdir='rmdir -vi'

# java.
alias j='java'
alias jc='javac'

# python.
alias py='python3'
alias pip='pip3'
alias python='python3'

# windows.
alias cls='clear'
alias copy='cp'
alias del='rm'
alias edit='vim'
alias move='mv'
alias rename='mv'

# config.
alias tmux='tmux -f ${XDG_CONFIG_HOME}/tmux/tmux.conf'
alias wget='wget --hsts-file=${XDG_CACHE_HOME}/wget-hsts'

# django.
alias dj='django-admin'
alias djch='dj check'
alias djdb='dj dbshell'
alias djdm='dj dumpdata'
alias djld='dj loaddata'
alias djm='dj migrate'
alias djmm='dj makemigrations'
alias djr='dj runserver'
alias djsa='dj startapp'
alias djsh='dj shell_plus --quiet-load --print-sql'
alias djsm='dj showmigrations'
alias djsp='dj startproject'
alias djsql='dj sqlmigrate'
alias djsu='dj createsuperuser'
alias djt='dj test --keepdb --pdb --failfast --noinput -v2'

# bat.
if command -v bat >/dev/null; then
  alias cat='bat'
fi

# coverage.
if command -v coverage >/dev/null; then
  alias cvrn='coverage run'
  alias cvrp='coverage report | less'
  alias cvht='coverage html'
fi

# exa.
if command -v exa >/dev/null; then
  alias l='ls --oneline'
  alias ls='exa --icons --group-directories-first'
  alias ll='ls --long --git'
  alias la='ls --all'
fi

# httpie.
if command -v http >/dev/null; then
  alias http='http --style=auto --unsorted'
fi

# ipython3.
if command -v ipython3 >/dev/null; then
  alias ipy='ipython3'
  alias ipython='ipython3'
fi

# nvim.
if command -v nvim >/dev/null; then
  alias vi='nvim'
  alias vim='nvim'
fi

# rmtrash.
if command -v rmtrash >/dev/null; then
  alias rm='rmtrash'
  alias rmdir='rmdirtrash'
fi

# sqlite3.
if command -v sqlite3 >/dev/null; then
  alias sqlite='sqlite3'
fi

# tree.
if command -v tree >/dev/null; then
  alias t='tree'
  alias tree='tree -C -I .git'
fi
