#!/bin/sh

# File:     django_aliases
# Created:  28.01.2021
# Author:   Artyom Danilov (@defytheflow)

alias dj='django-admin'
alias djch='dj check'
alias djdb='dj dbshell'
alias djdm='dj dumpdata'
alias djf='dj flush'
alias djld='dj loaddata'
alias djm='dj migrate'
alias djmm='dj makemigrations'
alias djr='dj runserver'
alias djsa='dj startapp'
alias djsh='dj shell_plus --quiet-load --print-sql'
alias djsm='dj showmigrations'
alias djsp='dj startproject'
alias djsql='dj sqlmigrate'
alias djsu='dj createsuperuser'
alias djt='dj test --keepdb --pdb --failfast --noinput -v2'
