#!/bin/sh

# File:     functions
# Created:  30.12.2019
# Author:   Artyom Danilov (@defytheflow)


# Prints number of entries in a directory.
n() {
    [ -n "${1}" ] && ls -A "${1}" | wc -l || ls -A | wc -l
}

# 'whereis' wrapper that lists every result on a separe line.
whereis() {
    command whereis "$@" | sed -e 's/ /\n/g'
}

# Reloads current running shell.
rld() {
    [ -n "${ZSH_NAME}" ] && exec zsh || [ -n "${BASH}" ] && . ~/.bashrc
}

# Sets background image.
setbg() {
    if [ -f "${1}" ] && command -v nitrogen >/dev/null; then
        nitrogen --head=xinerama --set-auto "${1}" && cp "${1}" "${WALLPAPER_HOME}"
    else
        return 1
    fi
}

# Sets terminal title.
title() {
    printf "\033]0;%s\007" "${*}"
}
