#!/bin/sh

# File:     functions
# Created:  30.12.2019
# Author:   Artyom Danilov


# 'whereis' wrapper that lists every result on a separe line.
whereis() {
    echo $(command whereis $*) | sed -e 's/ /\n/g'
}

# Reloads currently running shell.
rld() {
    [ -n "${ZSH_NAME}" ] && exec zsh || [ -n "${BASH}" ] && . ~/.bashrc
}

# Sets background image.
setbg() {
    if [ -f "${1}" ] && command -v nitrogen >/dev/null; then
        nitrogen --head=xinerama --set-auto "${1}" && cp "${1}" "${WALLPAPER_HOME}"
    else
        return 1
    fi
}

# Sets terminal title.
title() {
    printf "\033]0;%s\007" "${*}"
}

# Prints to the center of the terminal.
echoc() {
    width=$(stty size | cut -d ' ' -f2)
    length=${#1}
    printf "%$(( length + (width - length) / 2 ))b\n" "${1}"
}
