#!/bin/sh

# File:     functions
# Created:  30.12.2019
# Author:   Artyom Danilov (@defytheflow)

# Print number of entries in a directory.
n() {
  [ -n "${1}" ] && ls -A "${1}" | wc -l || ls -A | wc -l
}

# Reload current running shell.
rld() {
  [ -n "${ZSH_NAME}" ] && exec zsh || [ -n "${BASH}" ] && . ~/.bashrc
}

# Print each path entry on a newline.
path() {
  echo "${PATH}" | sed -e 's|:|\n|g'
}

# Print each whereis entry on a newline.
whereis() {
  command whereis "$@" | sed -e 's/ /\n/g'
}

# Set terminal title.
title() {
  printf "\033]0;%s\007" "${*}"
}

exc() {
  [ -z "${1}" ] && echo "${0}: <pattern> argument required." >&2 && return 1
  find . -maxdepth 1 -type f -not -name "${1}" -exec rm -v {} \;
}

# Set background image.
setbg() {
  if [ -f "${1}" ] && command -v nitrogen >/dev/null; then
    nitrogen --head=xinerama --set-auto "${1}" && cp "${1}" "${WALLPAPER_HOME}"
  else
    return 1
  fi
}
