#!/bin/sh

# File:      function
# Created:   30.12.2019
# Author:    Artyom Danilov


# Opens a pdf file for reading.
bread() {
    [ -n "${READER}" ] && [ -n "${1}" ] && ("${READER}" "${1}" &)
}

# Sets all passed arguments as terminal title.
title() {
    printf "\033]0;%s\007" "$*"
}

# Print first passed argument to the center of the terminal.
echoc() {
    width=$(stty size | cut -d ' ' -f2)
    length=${#1}
    printf "%$(( length + (width - length) / 2 ))b\n" "${1}"
}
