#!/bin/sh

# File:     arch
# Created:  29.07.2020
# Author:   Artyom Danilov (@defytheflow)

update_system() {
  log 'Updating arch system.'

  if command -v yay >/dev/null; then
    yay -Syu --noconfirm && yay -Yc --noconfirm
  else
    sudo pacman -Syu --noconfirm
  fi
}

install_packages() {
  log 'Installing arch packages.'

  set -- \
    alacritty awesome \
    bat \
    cargo chromium clang \
    dash \
    fzf \
    i3-gaps i3lock i3status \
    jq \
    gdb \
    luarocks \
    maven mlocate \
    neovim nitrogen npm \
    powerline-fonts python-neovim python-pip \
    ranger ripgrep rofi ruby \
    screenkey shellcheck shfmt \
    tk tmux tree ttf-fira-code \
    ueberzug \
    valgrind vim vi \
    xclip xcompmgr \
    yay \
    zathura zathura-pdf-mupdf zsh

  for pack; do
    log "Checking that $(color "${pack}") exists."
    sudo pacman -Qi "${pack}" >/dev/null || sudo pacman -S --noconfirm "${pack}"
  done

  set -- code rmtrash betterlockscreen java-language-server ccrypt

  for pack; do
    log "Checking that $(color "${pack}") AUR package exists."
    yay -Qi "${pack}" >/dev/null || yay -S --noconfirm "${pack}"
  done
}
