#!/bin/sh

# File:         arch
# Created:      29.07.2020
# Author:       Artyom Danilov (@defytheflow)

update_system() {
  if command -v yay >/dev/null; then
    yay -Syu --noconfirm && yay -Yc --noconfirm
  else
    sudo pacman -Syu --noconfirm
  fi
}

install_packages() {
  log 'Installing arch packages.'

  set -- \
    alacritty \
    bat \
    cargo clang \
    dash \
    i3-gaps i3lock \
    jq \
    gdb \
    mlocate \
    neovim nitrogen npm \
    powerline-fonts python-neovim python-pip \
    ripgrep rofi \
    screenkey shellcheck shfmt \
    tk tmux tree ttf-fira-code \
    valgrind vim \
    xclip xcompmgr \
    yay \
    zathura zathura-pdf-mupdf zsh

  for package; do
    log "Checking that $(color "${package}") exists."
    sudo pacman -Qi "${package}" >/dev/null || sudo pacman -S "${package}"
  done

  set -- code rmtrash

  for package; do
    log "Checking that $(color "${package}") exists."
    yay -Qi "${package}" >/dev/null || yay -S --noconfirm "${package}"
  done
}
