#!/bin/sh

# File:     mac
# Created:  16.03.2021
# Author:   Artyom Danilov (@defytheflow)

log "Running ${1} module."

install_packages() {
  log 'Installing brew packages.'

  install_brew() {
    log "Checking that $(color brew) exists."

    if ! command -v brew >/dev/null; then
      xcode-select --install
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
  }

  install_brew

  set -- \
    exa \
    iterm2 \
    keycastr \
    neovim node \
    pipenv postgresql


  for pack; do
    log "Checking that $(color "${pack}") exists."
    package_exists "${pack}" || brew install "${pack}"
  done
}

package_exists() {
  brew ls --versions "${1}" >/dev/null
}