#!/bin/sh

# File:      .xprofile
# Created:   28.03.2020
# Author:    Artyom Danilov

# Set wallpaper.
command -v nitrogen && nitrogen --head=xinerama --set-auto ~/.config/wallpaper

# Swap <CapsLock> and <Escape>.
setxkbmap -option 'caps:swapescape'

# Enable russian keyboard <Shift-Alt>.
setxkbmap -layout us,ru -option 'grp:alt_shift_toggle'
