
" File:     vimrc
" Created:  26.06.2020
" Author:   Artyom Danilov


" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Jump to the last position when reopening a file.
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

let g:mapleader = ';'

set nocompatible
set mouse=a         " enable mouse usage in all modes.
set encoding=utf-8
set hidden          " hide buffers when they are abandoned.
set autowrite       " automatically save before commands like :next and :make.
set viminfo+=n${XDG_CACHE_HOME}/vim/viminfo

syntax on
filetype plugin indent on  " load indentation rules and plugins according to the detected filetype.

set nobackup
set noswapfile

colorscheme codedark
set termguicolors
set background=dark

set history=1000
set wildmode=longest,list,full  " autocompletion.

set expandtab
set softtabstop=4
set shiftwidth=4
set smartindent

set ruler
set showcmd
set showmatch  " show matching brackets.

set number relativenumber
set cursorline
set splitbelow splitright
set foldmethod=marker

set hlsearch
set incsearch
set smartcase

set nowrap
set textwidth=90
set colorcolumn=+0  " display colorcolumn using &textwidth.

set list listchars=tab:>-,trail:-
if has('autocmd')
    au BufWritePre * %s/\s\+$//e           " remove trailing spaces.
    au BufWritePre * %s/\n\+\%$//e         " remove trailing newlines.
endif

if has('autocmd')
    au VimEnter * :NoMatchParen            " disable highlighting matching parentheses.
    au BufEnter * set fo-=c fo-=r fo-=o    " disable auto-commenting.
endif

au VimEnter * :NoMatchParen                " disable highlighting matching parentheses.

nnoremap <Space> za
nnoremap Y y$
nnoremap S :%s//g<Left><Left>

vnoremap < <gv
vnoremap > >gv

nnoremap <silent><leader>ev :split $MYVIMRC<CR>
nnoremap <silent><leader>sv :source $MYVIMRC<CR>
