#!/bin/sh

# File:      wsl/alias
# Created:   30.03.2020
# Author:    Artyom Danilov


alias calc='calc.exe'
alias cmd='cmd.exe'
alias explorer='explorer.exe'
alias notepad='notepad.exe'
alias powershell='powershell.exe'
alias write='write.exe'

alias chrome='${WIN_PROG_FILES_86}/Google/Chrome/Application/chrome.exe'
