#!/usr/bin/python3

# File:      pythonrc
# Created:   29.01.2020
# Modified:  28.03.2020
# Author:    Artyom Danilov
# Notes:     PYTHONSTARTUP environment variable must point to this file.


# To explore how coping works
from copy import copy, deepcopy

# To explore python compilation
from dis import dis

# To explore python objects
from inspect import (signature, ismodule, isclass, isfunction, isbuiltin, getsource)

# To print long datasets
from pprint import pprint

# To explore memory
from sys import getrefcount as refcount
from sys import getsizeof as sizeof

# To check the execution time of code
from timeit import timeit

# School modules.
try:
    from school import *
except ImportError:
    print("\n\tError: unable to load 'school' module.\n")

try:
    from interact import *
except ImportError:
    print("\n\tError: unable to load 'interact' module.\n")


def configure_history():
    ''' Change history default location and enable <Tab> completion. '''
    import atexit, os, readline

    history_path = os.path.expanduser("~/.cache/python/history")

    if os.path.exists(history_path):
        readline.read_history_file(history_path)

    atexit.register(lambda: readline.write_history_file(history_path))

    readline.parse_and_bind('tab: complete')


configure_history()
