#!/usr/bin/python3

# File:     pythonrc
# Created:  29.01.2020
# Author:   Artyom Danilov


def configure_history():
    ''' Change history default location and enable <Tab> completion. '''
    import atexit, os, readline

    history_path = os.path.expanduser(os.path.join(os.getenv('XDG_CACHE_HOME'), 'python', 'history'))

    if os.path.exists(history_path):
        readline.read_history_file(history_path)

    atexit.register(lambda: readline.write_history_file(history_path))

    readline.parse_and_bind('tab: complete')


configure_history()
