#!/usr/bin/zsh

# File:      zsh/function
# Purpose:   Define zsh-specific functions
# Created:   26.03.2020
# Modified:  28.03.2020
# Author:    Artyom Danilov


function shtype() {
# Echo shell type (login or interactive).
    [[ -o login ]] && print 'login' || print 'interactive'
}
