#!/bin/zsh

# File:      zsh/function
# Purpose:   Define functions for use during zsh interactive session.
# Notes:     This file is sourced by .zshrc

# Created:   26.03.2020
# Author:    Artyom Danilov


function shtype() {
# Echo shell type (login or interactive).
    [[ -o login ]] && print 'login' || print 'interactive'
}
