#!/usr/bin/zsh

# File:      zsh/prompt
# Purpose:   customize prompt
# Modified:  March 26, 2020
# Author:    Artyom Danilov

# Execute each time prompt is drawn.
function precmd() {
    # get last command exit status.
    if [ $? -eq 0 ]; then
        exit_status=" ${GREEN}:)"
    else
        exit_status=" ${RED}:("
    fi

    # get git branch.
    if branch="$(git branch 2>/dev/null)"; then
        branch=$(echo "${branch}" | colrm 1 2)
        branch="${WHITE} on ${CYAN}${branch}"
    fi

    # set PS1.
    PS1=$'\n'
    # if root, highlight everything in red.
    if [ "$(whoami)" = 'root' ]; then
        PS1+="${RED}%n"                     # root
        PS1+="${WHITE} at ${RED}%M"         # host
        PS1+="${WHITE} in ${RED}%~"         # absolute directory
    else
        PS1+="${PURPLE}%n"                  # username
        PS1+="${WHITE} at ${ORANGE}%M"      # host
        PS1+="${WHITE} in ${LIME_GREEN}%~"  # absolute directory
    fi
    PS1+="${branch}"                        # git branch
    PS1+="${exit_status}${RESET}"           # :) or :(
    PS1+=$'\n$ '
}
