#!/usr/bin/zsh

# File:      zsh/prompt
# Purpose:   customize prompt
# Modified:  March 26, 2020
# Author:    Artyom Danilov

# Executes each time prompt is drawn.
function precmd() {
    local branch exit_status

    # Get last command exit_status
    if [ $? -eq 0 ]; then
        exit_status=" ${GREEN}:)"
    else
        exit_status=" ${RED}:("
    fi

    # Get git branch.
    if branch="$(git branch 2>/dev/null)"; then
        branch=$(echo "${branch}" | colrm 1 2)
        branch="${WHITE} on ${CYAN}${branch}"
    fi

    # Set PS1
    PS1=$'\n'
    PS1+="${PURPLE}%n"                  # username
    PS1+="${WHITE} at ${ORANGE}%M"      # host
    PS1+="${WHITE} in ${LIME_GREEN}%~"  # absolute directory
    PS1+="${branch}"
    PS1+="${exit_status}${RESET}"       # :) or :(
    PS1+=$'\n$ '
}
