#!/usr/bin/zsh

# File:      .zshrc
# Purpose:   set user interactive configurations
# Modified:  March 26, 2020
# Author:    Artyom Danilov

# ------------------------------------------------------------------------------
#                                   Options
# ------------------------------------------------------------------------------

# Don't type cd to change directories.
setopt autocd autopushd

# Enable autocompletion.
autoload -Uz compinit
compinit

# Enable vim bindings.
bindkey -v

zstyle ':completion:*' menu select
zmodload zsh/complist

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

# Config files.

# Load shell-independent config files.
for file in "${HOME}/.dotfiles/shell/*"; do
    . "${file}"
done

# Load zsh-specific config files.
for file in 'alias' 'env' 'function' 'prompt'; do
    [ -f "${HOME}/.dotfiles/zsh/${file}" ] && . "${HOME}/.dotfiles/zsh/${file}"
done

# Check if running on wsl.
if grep -qEi '(Microsoft|WSL)' /proc/version > /dev/null 2>&1; then
    # Load wsl-specific config files.
    for file in "${HOME}/.dotfiles/wsl/*"; do
        . "${file}"
    done
fi

# Load plugins (must be last).
. ${ZSH_PLUGINS}/zsh-autosuggestions/zsh-autosuggestions.zsh
. ${ZSH_PLUGINS}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
. ${ZSH_PLUGINS}/alias-tips/alias-tips.plugin.zsh
