#!/usr/bin/zsh

# ------------------------------------------------------------------------------
# | File:      .zshenv
# ------------------------------------------------------------------------------
# | Modified:  March 23, 2020
# ------------------------------------------------------------------------------
# | Author:    Artyom Danilov
# ------------------------------------------------------------------------------

notify-send 'Running .zshenv'

# ------------------------------------------------------------------------------
#                                      C
# ------------------------------------------------------------------------------

# Compilation flags.
export CFLAGS='-W -Wall -Wextra'
# Search for includes here.
export CPATH="${HOME}/.lib/"
# Link libraries from here.
export LD_LIBRARY_PATH="${HOME}/.lib"

# ------------------------------------------------------------------------------
#                                     Git
# ------------------------------------------------------------------------------

# My github.
export GITHUB='https://github.com/defytheflow'
# My git-tracked projects directory.
export GITD="${HOME}/dev/git/"

# ------------------------------------------------------------------------------
#                                    Python
# ------------------------------------------------------------------------------

# Search python modules here.
export PYTHONPATH="${HOME}/.lib/"
# Run commands file.
export PYTHONRC="${HOME}/.dotfiles/python/pythonrc"
# Run this 'commands' file when starting interpreter.
export PYTHONSTARTUP="${PYTHONRC}"

# ------------------------------------------------------------------------------
#                                     zsh
# ------------------------------------------------------------------------------

export HISTCONTROL='ignoredups'
export HISTSIZE=10000
export HISTFILESIZE=10000

# Change default location of zsh config files.
export ZDOTDIR="${HOME}/.config/zsh"

# Standard config files.
export ZSHRC="${HOME}/.dotfiles/zsh/zshrc"
export ZSHENV="${HOME}/.dotfiles/zsh/zshenv"

# My config files.
export ZFUN="${HOME}/.dotfiles/zsh/zfun"
export ZALIAS="${HOME}/.dotfiles/zsh/zalias"
export ZPROMPT="${HOME}/.dotfiles/zsh/zprompt"

# ------------------------------------------------------------------------------
#                                  Shellcheck
# ------------------------------------------------------------------------------

# 1090 - can't follow source, 2034 - unused variable
export SHELLCHECK_OPTS='-e SC2034 -e SC1090'

# ------------------------------------------------------------------------------
#                                     Vim
# ------------------------------------------------------------------------------

# Use this as default editor by other programs.
export EDITOR='vim'

# Chande default vimrc location.
export VIMINIT='source $MYVIMRC'
export MYVIMRC="${HOME}/.dotfiles/vim/vimrc"

# Configuration file.
export VIMRC="${MYVIMRC}"
