#!/usr/bin/zsh

# ------------------------------------------------------------------------------
# | File:      .zshrc
# ------------------------------------------------------------------------------
# | Modified:  March 23, 2020
# ------------------------------------------------------------------------------
# | Author:    Artyom Danilov
# ------------------------------------------------------------------------------

notify-send 'Running .zshrc'

# ------------------------------------------------------------------------------
#                              Auto-Tab Complete
# ------------------------------------------------------------------------------

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files in autocomplete:
_comp_options+=(globdots)

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

# ------------------------------------------------------------------------------
#                         Aliases | Functions | Prompt
# ------------------------------------------------------------------------------

for file in 'zalias' 'zfun' 'zprompt'; do
        [ -f "${HOME}/.dotfiles/zsh/${file}" ] && . "${HOME}/.dotfiles/zsh/${file}"
done

# ------------------------------------------------------------------------------
#                                     WSL
# ------------------------------------------------------------------------------

# If running on wsl:
if grep -qEi '(Microsoft|WSL)' /proc/version > /dev/null 2>&1; then
    [ -f "${HOME}/.dotfiles/zsh/zwsl" ] && . "${HOME}/.dotfiles/zsh/zwsl"
fi

# ------------------------------------------------------------------------------
#                                   Plugins
# ------------------------------------------------------------------------------

# Must be last.
ZSH_PLUGINS=~/.dotfiles/zsh/plugins

source ${ZSH_PLUGINS}/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${ZSH_PLUGINS}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ${ZSH_PLUGINS}/alias-tips/alias-tips.plugin.zsh

