#!/bin/bash

# File:      bash/prompt
# Purpose:   Customize prompt
# Created:   26.03.2020
# Modified:  28.03.2020
# Author:    Artyom Danilov


# Execute each time prompt is drawn.
PROMPT_COMMAND=my_prompt

function my_prompt() {
    # get last command exit status.
    if [ $? -eq 0 ]; then
        local exit_status=" ${GREEN}:)"
    else
        local exit_status=" ${RED}:("
    fi

    # if root, highlight everything in red.
    if [ "$(whoami)" = 'root' ]; then
        PS1="\n${RED}\u"                    # root
        PS1+="${WHITE} at ${RED}\h"         # host
        PS1+="${WHITE} in ${RED}\w"         # absolute directory
    else
        PS1="\n${PURPLE}\u"                 # username
        PS1+="${WHITE} at ${ORANGE}\h"      # host
        PS1+="${WHITE} in ${LIME_GREEN}\w"  # absolute directory
    fi
    PS1+="${exit_status}${RESET}\n\$ "      # :) or :(
}
