#!/bin/bash

#  File:      bash/prompt
#  Purpose:   customize prompt
#  Modified:  March 26, 2020
#  Author:    Artyom Danilov

# Executes each time prompt is drawn.
PROMPT_COMMAND=my_prompt

function my_prompt() {
    local branch exit_status

    # Get last command exit_status
    if [ $? -eq 0 ]; then
        exit_status=" ${GREEN}:)"
    else
        exit_status=" ${RED}:("
    fi

    # Get git branch.
    if branch="$(git branch 2>/dev/null)"; then
        branch=$(echo "${branch}" | colrm 1 2)
        branch="${WHITE} on ${CYAN}${branch}"
    fi

    # Set PS1
    PS1="\n${PURPLE}\u"                 # username
    PS1+="${WHITE} at ${ORANGE}\h"      # host
    PS1+="${WHITE} in ${LIME_GREEN}\w"  # absolute directory
    PS1+="${branch}"
    PS1+="${exit_status}${RESET}\n\$ "  # :) or :(
}
